baseURL = "https://thamm.cloud"
title = "Eduard Thamm"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 6

[markup.highlight]
noClasses = false

[params]
author = "Eduard Thamm"
description = "Eduard's personal website"
keywords = "engineer,personal,tech lead,staff+"
info = ["Architecture","Reliability","Leadership"]
avatarURL = "./me.jpg"
dateFormat = "January 2, 2006"
since = 2018
# Right To Left, shift content direction for languages such as Arabic
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []
# Custom remote JS files
customRemoteJS = []

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"


# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive â€“ defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 1
url = "https://gitlab.com/edthamm"

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 2
url = "https://github.com/edthamm"

[[params.social]]
name = "GitHub Work"
icon = "fa-brands fa-square-github fa-2x"
weight = 2
url = "https://github.com/eduardOrthopy"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/ethamm"

[languages.en]
languageName = ":uk:"

# [[languages.en.menu.main]]
# name = "Blog"
# weight = 1
# url = "posts/"

[[languages.en.menu.main]]
name = "Talks"
weight = 1
url = "talks/"

[[languages.en.menu.main]]
name = "Library"
weight = 2
url = "library/"

[[languages.en.menu.main]]
name = "About"
weight = 3
url = "about/"

# [[languages.en.menu.main]]
# name = "Projects"
# weight = 3
# url = "projects/"

# [[languages.en.menu.main]]
# name = "Contact me"
# weight = 5
# url = "contact/"
